/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppLearningsRouteImport } from './routes/_app.learnings'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppRepositoriesIndexRouteImport } from './routes/_app.repositories.index'
import { Route as AppRepositoriesRepoIdRouteImport } from './routes/_app.repositories.$repoId'
import { Route as AppReportsReviewIdRouteImport } from './routes/_app.reports.$reviewId'
import { Route as AppRepositoriesRepoIdPullsPrNumberRouteImport } from './routes/_app.repositories.$repoId.pulls.$prNumber'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
})
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
})
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
})
const AppLearningsRoute = AppLearningsRouteImport.update({
  id: '/learnings',
  path: '/learnings',
  getParentRoute: () => AppRoute,
})
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
})
const AppRepositoriesIndexRoute = AppRepositoriesIndexRouteImport.update({
  id: '/repositories/',
  path: '/repositories/',
  getParentRoute: () => AppRoute,
})
const AppRepositoriesRepoIdRoute = AppRepositoriesRepoIdRouteImport.update({
  id: '/repositories/$repoId',
  path: '/repositories/$repoId',
  getParentRoute: () => AppRoute,
})
const AppReportsReviewIdRoute = AppReportsReviewIdRouteImport.update({
  id: '/$reviewId',
  path: '/$reviewId',
  getParentRoute: () => AppReportsRoute,
})
const AppRepositoriesRepoIdPullsPrNumberRoute =
  AppRepositoriesRepoIdPullsPrNumberRouteImport.update({
    id: '/pulls/$prNumber',
    path: '/pulls/$prNumber',
    getParentRoute: () => AppRepositoriesRepoIdRoute,
  })

const AppReportsRouteChildren = {
  AppReportsReviewIdRoute: AppReportsReviewIdRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

const AppRepositoriesRepoIdRouteChildren = {
  AppRepositoriesRepoIdPullsPrNumberRoute:
    AppRepositoriesRepoIdPullsPrNumberRoute,
}

const AppRepositoriesRepoIdRouteWithChildren =
  AppRepositoriesRepoIdRoute._addFileChildren(
    AppRepositoriesRepoIdRouteChildren,
  )

const AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppLearningsRoute: AppLearningsRoute,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppRepositoriesRepoIdRoute: AppRepositoriesRepoIdRouteWithChildren,
  AppRepositoriesIndexRoute: AppRepositoriesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)

import type { getRouter } from './router.jsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
